apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
      - name: allow-access
        image: busybox:1.28
        command: ['chown', '-R', '1000:1000', '/blah']
        volumeMounts:
        - mountPath: /blah
          name: data-blah
      containers:
      - name: myapp
        image: cklein/node-hostname:0.0.2
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /blah
          name: data-blah
      volumes:
        - name: data-blah
          persistentVolumeClaim:
            claimName: data-blah
