apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: '{{ .Release.Name }}'
spec:
  selector:
    matchLabels:
      app: '{{ .Release.Name }}'
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}'
    spec:
      containers:
      - name: myapp
        image: 'cklein/node-hostname:{{ .Values.image.tag }}'
        ports:
        - containerPort: 3000
