apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}'
spec:
  rules:
  - host: '{{ .Values.host }}'
    http:
      paths:
        - path: /
          backend:
            serviceName: '{{ .Release.Name }}'
            servicePort: 3000
